### ISSUE TITLE
[DESIGN] 계정 설정 페이지 퍼블리싱

### ISSUE THREAD

**Issue by AAminha** [Neighbors-dev/Frontend#12]
## 1️⃣ DESCRIPTION

- 계정 설정 페이지를 퍼블리싱 합니다.

## 2️⃣ TODO

- [x] 헤더
  - [x] 뒤로 가기 버튼 & 현재 페이지 이름
- [x] 닉네임 & 변경 버튼
  - [x] 닉네임 페이지 활용해서 닉네임 변경 페이지 연결
- [x] 약관 및 정책
- [x] 로그아웃
- [x] 탈퇴하기

## 3️⃣ ETC

- 기타사항
