### ISSUE TITLE
[DESIGN] 작성 페이지 퍼블리싱

### ISSUE THREAD

**Issue by AAminha** [Neighbors-dev/Frontend#13]
## 1️⃣ DESCRIPTION

- 작성 페이지를 퍼블리싱 합니다.

## 2️⃣ TODO

- [x] 대상 여부 페이지
- [x] 경찰, 소방 선택 페이지
- [x] 정보 입력 페이지
- [x] 검색 페이지
- [x] 작성 페이지
- [x] 감사메시지 모아보기
- [x] 소식 모아보기
- [x] 설명 팝업
- [x] 알림 여부 팝업
- [x] 공유 팝업

## 3️⃣ ETC

- 기타사항
