### ISSUE TITLE
[FEATURE] 공지사항 상세 조회 및 닉네임 변경 API 연동

### ISSUE THREAD

**Issue by AAminha** [Neighbors-dev/Frontend#15]
## 1️⃣ DESCRIPTION

- 공지사항 상세 조회 및 닉네임 변경 API 연동

## 2️⃣ TODO

- [x] 모킹 제거
- [x] 닉네임 변경 API 연동
- [x] 공지사항 상세 조회 API 연동
- [x] 로그아웃 임시 로직

## 3️⃣ ETC

- 기타사항
