### ISSUE TITLE
[DESIGN] 메인 페이지 퍼블리싱

### ISSUE THREAD

**Issue by AAminha** [Neighbors-dev/Frontend#6]
## 1️⃣ DESCRIPTION

- 메인 페이지를 퍼블리싱 합니다.

## 2️⃣ TODO

- [x] 헤더
  - [x] 로고 & 메뉴 버튼
- [x] 공지 컴포넌트
- [x] 카운트
- [x] 메시지 작성 버튼
- [x] 현재 작성된 메시지 리스트

## 3️⃣ ETC

- 기타사항
